- name: Install 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: yes
  become: yes    
  
  tasks:

      
      - name: Start project
        shell: 
          cmd: docker-compose up -d
          chdir: "{{ git_dst }}"
        register: docker_output

      - name: Add a container to a network, leaving existing containers connected
        docker_network:
          name: "{{ network_name }}"
          connected:
            - "{{ arweave }}"
          appends: yes

     