- name: Install 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: yes
  become: yes    
  
  tasks:

      
      - name: Git checkout
        ansible.builtin.git:
          repo: '{{ git_url }}'
          dest: "{{ git_dst }}"
          remote: origin
          branch: master
          update: yes
          track_submodules: true
        register: git_pull_output
            
  
      - name: Update the project
        shell: 
          cmd: docker-compose up --build -d
          chdir: "{{ git_dst }}"
        register: docker_output
        when: git_pull_output.changed






      # - name: Create and start services
      #   community.docker.docker_compose:
      #     project_src: "{{ git_dst }}"
      #     pull: true
      #     detached: yes
      #   register: output
          
      

     